### PR TITLE
workflows: Upload results from encodings generation

### PR DESCRIPTION
**Pull request by pchaigno**
The output directory will contain both the generated encodings and the associated logs, all useful to debug issues.

### CODE REVIEW

**Comment by pchaigno** [comment]
@harishankarv This pull request uploads the results of the two CI workflows. You can see them on the workflow pages, under Artifacts.

If you check the one for LLVM-to-SMT (`bpf_encodings-5.9-BPF_AND.zip` for example), there are a bunch of files for various instructions at the root of the `bpf_encodings/5.9/` directory (the directory that is zipped). Any idea why? I expected to find stuff only under `bpf_encodings/5.9/BPF_AND/`.

**Comment by harishankarv** [comment]
@pchaigno thanks for setting this up!

> there are a bunch of files for various instructions at the root of the bpf_encodings/5.9/ directory (the directory that is zipped)
If I understand correctly, you're talking about why there is `BPF_OR.smt2`, `BPF_XOR.smt2` within the `5.9` directory? I checked, and this is not the case for the `6.8` directory: that only contains `BPF_AND.smt2`. I'm not sure where these extra files are coming from.

**Comment by pchaigno** [comment]
> It seems this is not the case for the `6.8` directory: that only contains `BPF_AND.smt2`, right?

Uh, you're right. Even weirder :sweat_smile: 

Anyway, let's ignore this for now to make progress. I'll upload just the subdir and will mark this PR ready for review.

**Review by harishankarv — APPROVED** [review]
Looks good to me!

**Comment by pchaigno** [comment]
> If I understand correctly, you're talking about why there is `BPF_OR.smt2`, `BPF_XOR.smt2` within the `5.9` directory? I'm not sure where these extra files are coming from.

@harishankarv It seems they are coming from this code: https://github.com/bpfverif/agni/blob/67a2eb673b08ae29e0b8a8a6e69259a2ae203205/llvm-to-smt/run_llvm_passes.py#L257-L259

Do you remember the reason for this?

**Comment by harishankarv** [comment]
This was done simply because  the verification `bpf_alu_jmp_synthesis.py` required all the encodings in one directory. After generating the encodings within the op directory e.g. `outdir/BPF_AND/BPF_AND.smt2`, the encoding is copied to parent directory, i.e. the main `outdir`. That way all the encodings `BPF_AND.smt2`, `BPF_OR.smt2` would lie in the same directory. 
If you do not plan to run `bpf_alu_jmp_synthesis.py` on the generated encodings, then `copy_encoding_to_parent_dir()` shouldn't matter.

**Comment by harishankarv** [comment]
Re: https://github.com/bpfverif/agni/actions/runs/9918518732
What I am wondering is where did the encodings for other ops  come from in the first place, to be copied into the parent directory copy from? You ran `generate_encodings.py` with `--specific-op BPF_AND`. That means there should have only been a `BPF_AND` directory created, and encoding for BPF_AND.smt2, which should have been copied into the parent directory.   

Also strange that the 6.8 artifact does not contain the other op encodings as I pointed out before.

**Comment by harishankarv** [comment]
Regardless, I believe we can address this if needed. This would be needed only if we plan to run `bpf_alu_jmp_synthesis.py` on generated encodings.

1. We can have `bpf_alu_jmp_synthesis.py` accept encodings from within op subdirectories. @mshachnai 
2. Copy the encodings into a separate directory say, `outdir/bpf_encodings` which  `bpf_alu_jmp_synthesis.py` can then read from:
`--encodings_path outdir/bpf-encodings/`

**Comment by pchaigno** [comment]
Why do we need the subdirectories and their content? If it's only for debugging, could we put it behind a flag?

**Pull request merged**
